# torchtitan Config.toml
# NOTE: this toml config is a preset for 128 H100 GPUs.

[job]
dump_folder = "./outputs"
description = "Llama 3 405B training"

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 10
enable_tensorboard = true
save_tb_folder = "tb"

[model]
name = "llama3"
flavor = "405B"
tokenizer_path = "./assets/tokenizer/original/tokenizer.model"
converters = ["float8"]

[optimizer]
name = "AdamW"
lr = 8e-5
eps = 1e-8

[lr_scheduler]
warmup_steps = 600  # lr scheduler warm up, normally 20% of the train steps

[training]
batch_size = 2
seq_len = 8192
max_norm = 1.0  # grad norm clipping
steps = 3000
compile = true
dataset = "c4"

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 8  # 8-way TP
enable_async_tensor_parallel = true
pipeline_parallel_degree = 1
context_parallel_degree = 1

[checkpoint]
enable_checkpoint = false
folder = "checkpoint"
interval = 500
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = "full" # ["none", "selective", "full"]

[float8]
enable_fsdp_float8_all_gather = true
precompute_float8_dynamic_scale_for_fsdp = true
filter_fqns = ["output"]
