# NOTE: this toml config is a preset for 8 H100 GPUs (with 96GiB memory).

[job]
dump_folder = "/home/dakota/training/image-gen-4b"
description = "image gen 4b training"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 1
enable_tensorboard = false
save_tb_folder = "tb"
enable_wandb = true

[model]
name = "qwen3"
flavor = "4B_vq_flex"
hf_assets_path = "/home/dakota/github/torchtitan/assets/hf/qwen3-4b-img-vq-expanded/"
# converters = ["float8"]

[optimizer]
name = "AdamW"
lr = 4e-4
eps = 1e-8

[lr_scheduler]
warmup_steps = 1000  # lr scheduler warm up, 10% total steps
decay_ratio = 0.1

[training]
local_batch_size = 3
seq_len = 16384
max_norm = 1.0  # grad norm clipping
steps = 10000
dataset = "gen_only"
dataset_type = "packed_memmap"
global_batch_size = 384

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
fsdp_reshard_after_forward = "default" # default / never / always
tensor_parallel_degree = 1
context_parallel_degree = 1

[checkpoint]
enable = true
folder = "checkpoint"
interval = 500
initial_load_in_hf = true
last_save_model_only = true
last_save_in_hf = true
export_dtype = "bfloat16"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = "selective"  # ["none", "selective", "full"]
selective_ac_option = "op"  # "int" = ac every positive int layer or 'op', ac based on ops policy

[compile]
enable=true
components = ["model", "loss"]

[quantize.linear.float8]
enable_fsdp_float8_all_gather = false
precompute_float8_dynamic_scale_for_fsdp = false
filter_fqns = ["output"]
