# Based on config10b0_like_config9bb0_qwen3_30b_a3b_with_deepep_and_with_force_load_balance.toml
# sync_comm_stream=false, fused_weighted_scatter_add=false, fused_silu_gate_prob=true

[job]
dump_folder = "./outputs"
description = "Qwen3 32B training with DeepEP"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 10
enable_tensorboard = false
save_tb_folder = "tb"
enable_wandb = true

[model]
name = "qwen3"
flavor = "30B-A3B-deepep"
hf_assets_path = "./assets/hf/Qwen3-32B"

[optimizer]
name = "AdamW"
lr = 8e-4
eps = 1e-8

[lr_scheduler]
warmup_steps = 600

[training]
local_batch_size = 8
seq_len = 4096
max_norm = 1.0
steps = 20
dataset_type = "nanoset"
dataset_folders = ["/home/shared/datasets/fineweb-edu-v1_4-tokenized-qwen3", "/home/shared/datasets/dclm-baseline-1.0-tokenized-qwen3"]
dataset_weights = [1, 1]
debug_moe_force_load_balance=false

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
fsdp_reshard_after_forward = "default"
tensor_parallel_degree = 1
context_parallel_degree = 1
expert_parallel_degree = 8

[checkpoint]
enable = false
folder = "checkpoint"
interval = 500
last_save_model_only = false
export_dtype = "float16"
async_mode = "disabled"

[activation_checkpoint]
mode = "full"
selective_ac_option = "op"

[compile]
enable=true
components = ["model", "loss"]

[quantize.linear.float8]
enable_fsdp_float8_all_gather = false
precompute_float8_dynamic_scale_for_fsdp = false
filter_fqns = ["output"]

[deepep]
sync_comm_stream = false
fused_weighted_scatter_add = false
fused_silu_gate_prob = true

[debug]
moe_force_load_balance = false
