# torchtitan Config.toml
[job]
dump_folder = "./outputs"
description = "LLaMA 13B training"

[profiling]
run_profiler = true
save_traces_folder = "profiling/traces"
profile_freq = 100

[metrics]
log_freq = 10
enable_tensorboard = true
save_tb_folder = "tb"

[model]
name = "llama"
flavor = "13B"
norm_type = "rmsnorm" # [layernorm, np_layernorm, rmsnorm, fused_rmsnorm]
tokenizer_path = "./torchtitan/datasets/tokenizer/tokenizer.model"

[optimizer]
name = "AdamW"
lr = 3e-4

[training]
batch_size = 16
seq_len = 4096
warmup_steps = 200  # lr scheduler warm up, normally 20% of the train steps
max_norm = 1.0  # grad norm clipping
steps = 1000
data_parallel_degree = -1
tensor_parallel_degree = 8  # 8-way TP, adjust to 2/4 for local (single host) runs
pipeline_parallel_degree = 1
fp8_linear = ""
compile = false
dataset = "openwebtext"

[checkpoint]
interval = 500
interval_type = "steps"
folder = ""
model_weights_only = false
export_dtype = "float32"

[activation_checkpoint]
mode = 'selective'  # ['none', 'selective', 'full']
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy
