# torchtitan Config.toml

[job]
dump_folder = "./outputs"
description = "Llama2 7B training"

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 20

[metrics]
log_freq = 1
enable_tensorboard = false
save_tb_folder = "tb"

[model]
name = "llama2"
flavor = "7B"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm / fused_rmsnorm
tokenizer_path = "/mnt/petrelfs/share_data/caizheng/tokenizer.model"

[optimizer]
name = "AdamW"
lr = 1e-4

[training]
batch_size = 8
seq_len = 2048
warmup_steps = 10  # lr scheduler warm up, 0.01 of the train steps
max_norm = 1.0  # grad norm clipping
steps = 1000
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1  # dp-only would be sufficient for 7B
compile = false
dataset = "tinystories"

[experimental]
context_parallel_degree = 1
pipeline_parallel_degree = 1

[checkpoint]
enable_checkpoint = false
folder = "checkpoint"
interval_type = "steps"
interval = 500
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'selective'  # ['none', 'selective', 'full']
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = false
