# torchtitan Config.toml
# NOTE: this toml config is a preset for 64 A100 GPUs.

[job]
dump_folder = "./outputs"
description = "LLaMA 70B training"

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
# profiling frequency - example: 10 means every 10th iter will be profiled
profile_freq = 100

[metrics]
log_freq = 10
enable_tensorboard = true
save_tb_folder = "tb"

[model]
name = "llama"
flavor = "70B"
norm_type = "rmsnorm" # [layernorm, np_layernorm, rmsnorm, fused_rmsnorm]
tokenizer_path = "./torchtitan/datasets/tokenizer/tokenizer.model"

[optimizer]
name = "AdamW"
lr = 1.5e-4

[training]
batch_size = 16
seq_len = 4096
warmup_steps = 200  # lr scheduler warm up, normally 20% of the train steps
max_norm = 1.0  # grad norm clipping
steps = 1000
data_parallel_degree = -1
tensor_parallel_degree = 8  # 8-way TP
pipeline_parallel_degree = 1
fp8_linear = ""
compile = false
dataset = "openwebtext"

[checkpoint]
enable_checkpoint = false
checkpoint_folder = "checkpoint"
interval_type = "steps"
interval = 500
model_weights_only = false
export_dtype = "float32"

[activation_checkpoint]
mode = 'full'  # ['none', 'selective', 'full']
