# Exp1aa6: 8 nodes EP=64 CP=2 LBS=2 ctx=24k
[job]
dump_folder = "./outputs/exp1a/exp1aa6_8n_EP64_CP2_LBS2_ctx24k"
description = "exp1aa6_8n_EP64_CP2_LBS2_ctx24k"

[profiling]
enable_profiling = false

[metrics]
log_freq = 1

[model]
name = "deepseek_v3"
flavor = "kimi_k2"
hf_assets_path = "./assets/hf/DeepSeek-V3-Base"

[optimizer]
name = "AdamW"
lr = 2.2e-4

[lr_scheduler]
warmup_steps = 2
decay_ratio = 0.8

[training]
local_batch_size = 2
seq_len = 24576
steps = 5
dataset = "c4_test"
enable_cpu_offload = true
clear_cache_between_steps = true
skip_optimizer_step = true

[parallelism]
data_parallel_shard_degree = -1
expert_parallel_degree = 64
context_parallel_degree = 2

[activation_checkpoint]
mode = "full"

[compile]
enable = false

[debug]
moe_force_load_balance = true
